# Default values for lakefs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
postgresql:
  auth:
    enablePostgresUser: false
    existingSecret: "postgres-secret"
    username: "lakefs"
    database: "lakefs"
  primary:
    resources:
      limits:
        ephemeral-storage: 500Mi
        memory: 2Gi
        cpu: 1

lakefs:
  # Default values for lakefs.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  replicaCount: 1

  image:
    repository: treeverse/lakefs
    pullPolicy: Always

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      #upload size settings
      nginx.ingress.kubernetes.io/client-body-buffer-size: '16m'
      nginx.ingress.kubernetes.io/proxy-body-size: '1g'
      # Request/response buffering (on for upload safety)
      nginx.ingress.kubernetes.io/proxy-buffering: 'on'
      nginx.ingress.kubernetes.io/proxy-request-buffering: 'on'
      nginx.ingress.kubernetes.io/proxy-max-temp-file-size: '2000m'
      # timeout settings for resources
      nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
      nginx.ingress.kubernetes.io/proxy-connect-timeout: '60'
      nginx.ingress.kubernetes.io/send-timeout: '300'
      nginx.ingress.kubernetes.io/upstream-keepalive-timeout: '60'
      # http support
      nginx.ingress.kubernetes.io/proxy-http-version: '1.1'
      #cors and upstream settings
      nginx.ingress.kubernetes.io/enable-cors: 'true'
      nginx.ingress.kubernetes.io/service-upstream: 'true'
      nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0,::/0
    ingressClassName: ""
    defaultBackend: {}
    hosts:
#      - host: ""
#        paths:
#          - "/"
#        # redirect to a different service based on path prefix for advanced use cases only
#        # pathsOverrides:
#        #   - path: /some/path
#        #     serviceName: other-example.local
#        #     servicePort: 80
#    tls:
#     - secretName: ""
#       hosts:
#         - ""
  podAnnotations: {}
  deployment:
    port: 8000

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      memory: 4Gi
      cpu: 2

  s3Fallback:
    enabled: false
    
  committedLocalCacheVolume:
    name: committed-local-cache
    persistentVolumeClaim:
      claimName: committed-local-cache

  secrets:
    authEncryptSecretKey:  ""
    databaseConnectionString: postgres://lakefs:lakefs@lakefs-postgresql:5432/lakefs?sslmode=disable
  lakefsConfig: |
    logging:
      level: TRACE
    database:
      type: postgres
      postgres:
        connection_max_lifetime: 3h
    blockstore:
      type: local
      local:
        path: "/data"

  # yamllint disable rule:comments

  # Example: using node instance storage for caching committed data:
  # For more information: https://www.vipmind.me/infra/aws/how-to-use-ephemeral-disk-from-ec2-instance-in-eks.html
  #committedLocalCacheVolume:
  #  hostPath:
  #    path: /media/ephemeral0

  # yamllint enable

  serviceAccount: {}

  # Extra Environment Values - allows yaml definitions
  extraEnvVars:
  #  - name: VALUE_FROM_SECRET
  #    valueFrom:
  #      secretKeyRef:
  #        name: secret_name
  #        key: secret_key
  # Override K8S defaults for readinessProbe
  # readinessProbe:
  #   failureThreshold: 10
  #   periodSeconds: 5
  #   successThreshold: 4
  #   timeoutSeconds: 1
  # Override K8S defaults for livenessProbe
  # livenessProbe:
  #   failureThreshold: 20
  #   periodSeconds: 5
  #   successThreshold: 4
  #   timeoutSeconds: 1
  #   initialDelaySeconds: 5

  # Start local postgres pod for quick start, not for production
  useDevPostgres: true
  dataVolume:
    name: "lakefs-local-data"
    size: 1500Gi
    storageClassName: "basic"
  extraVolumeMounts:
  - mountPath: /data
    name: lakefs-local-data
  extraVolumes: 
  - name: lakefs-local-data
    persistentVolumeClaim:
       # same as lakfs.dataVolume.name
      claimName: lakefs-local-data
#  - name: committed-local-cache
#    persistentVolumeClaim:
#      # same as lakfs.dataVolume.name
#      claimName: committed-local-cache
cache_size: 10Gi