{{ if .Values.lakefs.dataVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.lakefs.dataVolume.name }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  storageClassName: {{ .Values.lakefs.dataVolume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.lakefs.dataVolume.size }}
  accessModes:
    - ReadWriteOnce
{{ end }}
---
{{ if  .Values.lakefs.committedLocalCacheVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.lakefs.committedLocalCacheVolume.name }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  {{ if  .Values.lakefs.committedLocalCacheVolume.storageClassName }}
  storageClassName: {{ .Values.lakefs.committedLocalCacheVolume.storageClassName }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.lakefs.committedLocalCacheVolume.size }}
  accessModes:
    - ReadWriteOnce
{{ end }}

