apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.lakefs.dataVolume.name }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  storageClassName: {{ .Values.lakefs.dataVolume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.lakefs.dataVolume.size }}
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.lakefs.committedLocalCacheVolume.name }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  storageClassName: {{ .Values.lakefs.dataVolume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.cache_size }}
  accessModes:
    - ReadWriteMany